package ru.ipo.dces.plugins.admin;

import ru.ipo.dces.pluginapi.Plugin;
import ru.ipo.dces.pluginapi.PluginEnvironment;

import javax.swing.*;

import com.jgoodies.forms.layout.FormLayout;
import com.jgoodies.forms.layout.CellConstraints;

/**
 * Created by IntelliJ IDEA.
 * User: Michael Kazekin
 * Date: 11.11.2008
 * Time: 20:13:25
 * To change this template use File | Settings | File Templates.
 */
public class ManageContestsPlugin extends Plugin {
    private JPanel panel1;
    private JList list1;

    /**
     * Инициализация plugin'а
     */
    public ManageContestsPlugin(PluginEnvironment env) {
        super(env);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:122px:noGrow,left:4dlu:noGrow,fill:max(d;4px):noGrow", "center:max(d;4px):noGrow,top:4dlu:noGrow,center:16px:noGrow,top:4dlu:noGrow,center:428px:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        list1 = new JList();
        CellConstraints cc = new CellConstraints();
        panel1.add(list1, cc.xy(3, 5, CellConstraints.DEFAULT, CellConstraints.FILL));
        final JLabel label1 = new JLabel();
        label1.setText("Доступные контесты");
        panel1.add(label1, cc.xy(3, 3));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
