package ru.ipo.dces.plugins.admin;

import ru.ipo.dces.pluginapi.Plugin;
import ru.ipo.dces.pluginapi.PluginEnvironment;
import ru.ipo.dces.client.Controller;
import ru.ipo.dces.clientservercommunication.*;

import javax.swing.*;

import com.jgoodies.forms.layout.FormLayout;
import com.jgoodies.forms.layout.CellConstraints;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 * Created by IntelliJ IDEA.
 * User: Илья
 * Date: 11.12.2008
 * Time: 20:06:45
 */
public class LogoutPlugin extends JPanel implements Plugin {
  private JButton logoutButton;
  private JPanel mainPanel;
  private JButton refreshButton;

  /**
   * Инициализация plugin'а
   *
   * @param env environment for the plugin
   */
  public LogoutPlugin(PluginEnvironment env) {
    $$$setupUI$$$();
    env.setTitle("- Управление -");

    logoutButton.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent e) {
        if (JOptionPane.showConfirmDialog(null, "Действительно выйти?",
                "Подтверждение", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
          Controller.logout();
      }
    });
    refreshButton.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent e) {
        if (Controller.getUserType() != UserDescription.UserType.Participant) {
          JOptionPane.showMessageDialog(null, "Только участники могут обновлять список задач");
          return;
        }

        try {
          Controller.getClientDialog().clearLeftPanel();
          //the first plugin will be selected after this call
          Controller.refreshParticipantInfo();
          JOptionPane.showMessageDialog(null, "Условия успешно обновлены");
        } catch (Exception ee) {
          JOptionPane.showMessageDialog(null, "Не удалось обновить условия");
          Controller.getClientDialog().initialState();
        }
      }
    });
  }

  private void createUIComponents() {
    mainPanel = this;
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    createUIComponents();
    mainPanel.setLayout(new FormLayout("fill:max(d;4px):grow,left:4dlu:noGrow,fill:160dlu:noGrow,left:4dlu:noGrow,fill:80dlu:noGrow,left:4dlu:noGrow,fill:max(d;4px):grow", "center:12dlu:noGrow,top:4dlu:noGrow,center:20dlu:noGrow,top:8dlu:noGrow,center:20dlu:noGrow"));
    final JLabel label1 = new JLabel();
    label1.setText("Прекратить участие в контесте");
    CellConstraints cc = new CellConstraints();
    mainPanel.add(label1, cc.xy(3, 3));
    final JLabel label2 = new JLabel();
    label2.setText("Обновить условия задачи");
    mainPanel.add(label2, cc.xy(3, 5));
    logoutButton = new JButton();
    logoutButton.setText("Выход");
    mainPanel.add(logoutButton, cc.xy(5, 3));
    refreshButton = new JButton();
    refreshButton.setText("Обновить");
    mainPanel.add(refreshButton, cc.xy(5, 5));
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return mainPanel;
  }

  public JPanel getPanel() {
    return this;
  }

  public void activate() {
    //do nothing
  }

  public void deactivate() {
    //do nothing
  }
}
